export type InterviewContext = "personal" | "behavioral";

const INTERVIEW_CONTEXT_BY_ID: Record<string, InterviewContext> = {
  "casual/hometown": "personal",
  "casual/travel-recommendation": "personal",
  "casual/hobby-origin": "personal",
  "casual/favorite-movie": "personal",
  "casual/ideal-weekend": "personal",
  "casual/comfort-food": "personal",
  "casual/person-you-admire": "personal",
  "casual/recent-interest": "personal",
  "casual/new-skill": "personal",
  "casual/favorite-season": "personal",
  "casual/stress-relief": "personal",
  "casual/core-value": "personal",
  "casual/childhood-dream": "personal",
  "casual/favorite-place": "personal",
  "casual/memorable-event": "personal",
  "casual/book-recommendation": "personal",
  "casual/morning-routine": "personal",
  "casual/language-motivation": "personal",
  "casual/holiday-memory": "personal",
  "casual/stay-organized": "personal",
  "casual/music": "personal",
  "casual/social-media": "personal",
  "casual/advice-younger-self": "personal",
  "casual/meaningful-gift": "personal",
  "casual/typical-day": "personal",
  "casual/childhood-memory": "personal",
  "casual/family-influence": "personal",
  "casual/currently-learning": "personal",
  "casual/student-effort": "behavioral",
  "casual/teamwork": "behavioral",
  "casual/failure-lesson": "behavioral",
  "casual/tough-decision": "behavioral",
  "casual/proud-accomplishment": "behavioral",
  "casual/five-year-goal": "behavioral",
  "casual/leadership": "behavioral",
  "casual/conflict-resolution": "behavioral",
  "casual/mentor-influence": "behavioral",
  "casual/strength": "behavioral",
  "casual/weakness-improvement": "behavioral",
  "casual/career-choice": "behavioral",
  "casual/helped-someone": "behavioral",
  "casual/received-help": "behavioral",
  "casual/presentation": "behavioral",
  "casual/handling-pressure": "behavioral",
  "casual/cross-cultural": "behavioral",
  "casual/self-taught-skill": "behavioral",
  "casual/habit-changed": "behavioral",
  "casual/goal-achieved": "behavioral",
  "casual/stay-motivated": "behavioral",
  "casual/unexpected-challenge": "behavioral",
};

export function getInterviewContext(questionId: string): InterviewContext {
  return INTERVIEW_CONTEXT_BY_ID[questionId] ?? "personal";
}
